### PR TITLE
update docpress

### PR DESCRIPTION
**Pull request by brillout**
Update docpress to fix bug.

### CODE REVIEW

**Comment by brillout** [comment]
@hemengke1997 FYI, the following means that `headings.ts` needs to be updated.

```
[DocPress][Wrong Usage] Page section title not found for <Link href="`/cloudflare-workers#cloudflare-pages`" doNotInferSectionTitle={true} />.
```

```ts
// headings.tsx

   {
     level: 2,
     title: 'Cloudflare Workers',
     url: '/cloudflare-workers',
     // TODO
     // sectionTitles: ["Cloudflare Pages"],
   },
```

**Comment by hemengke1997** [comment]
Thank you!

**Comment by hemengke1997** [comment]
image

Seems that the problem is still there.

Once `docpress` compile markdown `heading`, like: `#`. The error occurred.

I guess it's because https://github.com/brillout/docpress/blob/main/src/markdownHeadingsVitePlugin.ts#L27

**Comment by brillout** [comment]
I know. Since the error is originating from acorn I'm leaning more towards thinking that it's a problem somewhere in MDX.

In the meantime, we can use GH actions to deploy. So I don't think it's a hard blocker (annoying for you though since you can't locally test whether the build works).

**Comment by hemengke1997** [comment]
Yes, it's really annoying. It even affects my development, because I have to comment the heading.

**Comment by brillout** [comment]
Ok, that's bad.

What's the string acorn receives which makes acorn error out?

**Comment by brillout** [comment]
(I don't have a windows machine, so it's hard for me to get that information: I'd need to patch MDX and run it against a windows GitHub Action, quite cumbersome.)

**Comment by hemengke1997** [comment]
> Ok, that's bad.
> 
> What's the string acorn receives which makes acorn error out?

If I understand correctly, the problem is caused by '#'

**Comment by brillout** [comment]
I need the entire string that is being passed to `acorn`.

**Comment by hemengke1997** [comment]
> I need the entire string that is being passed to `acorn`.

Ok, sorry. I can reproduce the problem by:

test.mdx
```mdx
# Hello world
```

I don't know whether this is the entire string you need

**Pull request merged**
